### ISSUE TITLE
[Feature Request] /filter » Remove all messages containing a specific keyword 

### ISSUE THREAD

**Issue by nsde** [JH220/discord-clearchatbot#14]
### Requires MCI (Message Content Intent)
***
# /filter
## Remove all messages containing a (or one of) certain keyword(s)

**Please** add this feature @JH220 as it is a way to protect privacy - say I'm in a server where I used to post a lot of messages about a topic I now dislike or which could be traced to my personal information. With this command, it would be possible to delete all messages from a user who doesn't want to share such information.

This can be extremely useful for clearing out messages that contain spam, too!

## Arguments
- STR: keywords, seperated by a space OR regex (if it's easy to program, it probably is tbh)
- BOOL/STR: mode
    - **and:** the message has to contain ALL of the said keywords
    - **or:** the message has to contain SOME of the said keywords
- USER: if none, select all users
- CHANNEL: if none, use all

```
/filter keywords:"hate slurs" mode:"or"
/filter keywords:"google facebook apple" mode:"or" user:@ONLIX channel:#general
/filter keywords:"bastighg good" mode:"and" user:@ONLIX channel:#opinions
```

The last one was a joke.

**Comment by JH220** [comment]
Not possible, because the Message Content Intent will be needed for this in the future.
