### ISSUE TITLE
Error-ID: 6131265473

### ISSUE THREAD

**Issue by l1GRIZZLY1l** [JH220/discord-clearchatbot#15]
**Describe the bug**
If you have an error ID, please include it here or in the title.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by l1GRIZZLY1l** [comment]
Fix the clear bot none of it works

**Comment by nsde** [comment]
Hello there, can you please tell me what the actual issue is and if there were any error messages while trying to run a command? Otherwise, I can't really help you. Also, please re-open the issue and fill in your answers correctly.
