### ISSUE TITLE
Error-ID: 8859429677

### ISSUE THREAD

**Issue by andreeei** [JH220/discord-clearchatbot#18]
**Describe the bug**
If you have an error ID, please include it here or in the title.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by w1nlove** [comment]
Error-ID: 8859429677

**Comment by nsde** [comment]
Hello there, thanks for submitting your error. Thanks to the Error ID, @JH220 is able to take a look into what caused the problems.
We'll reach out once the cause is clear. 
Thank you for understanding.

**Comment by JH220** [comment]
Hey, thanks for submitting your error.
I took a look at it, we are already aware of the bug and it is being fixed right now.
I hope the bot will again soon.

With kind regards
JH220
