### ISSUE TITLE
[Feature Request] Spam Blocker

### ISSUE THREAD

**Issue by nsde** [JH220/discord-clearchatbot#2]
A configurable way to filter messages, for example by:

- allowed or blacklisted domains
- filtering spam (ping) messages
- filtering certain keywords for certain roles

**Comment by JH220** [comment]
No longer so easily possible due to message intent.
Will therefore be closed for now.

**Comment by nsde** [comment]
![image](https://user-images.githubusercontent.com/67185896/147883559-714a492c-146d-4b2a-bc4d-004b12286bc0.png)
You're right, but the Discord blog indeed claims "Content moderation" as the **first accepted use case!**

**Comment by nsde** [comment]
@JH220 

![image](https://user-images.githubusercontent.com/67185896/147883559-714a492c-146d-4b2a-bc4d-004b12286bc0.png)
You're right, but the Discord blog indeed claims "Content moderation" as the **first accepted use case!**

**Comment by JH220** [comment]
Yes, you could do that if you would like to.
But I think it's too much work for me to apply for it, if it's only for one command.

**Comment by nsde** [comment]
> it's only for one command
Hmm, not really. At that moment, 2 commands would require such application.
It could be worth it, I mean you have **more than 273,269 members**! Don't give up yet!
