### ISSUE TITLE
Error-ID 2163875739

### ISSUE THREAD

**Issue by PJLUNS13** [JH220/discord-clearchatbot#20]
**Describe the bug**
If you have an error ID, please include it here or in the title.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by JH220** [comment]
Hey, thanks for submitting your error.
I took a look at it, we are already aware of the bug and it is being fixed right now.
I hope the bot will again soon.

With kind regards
JH220
