### ISSUE TITLE
Error-ID:  2819715399

### ISSUE THREAD

**Issue by DarioStar999** [JH220/discord-clearchatbot#21]
**Describe the bug**
If you have an error ID, please include it here or in the title.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by JH220** [comment]
Hey, thanks for submitting your error.
I took a look at it, we are already aware of the bug and it is being fixed right now.
I hope the bot will again soon.

With kind regards
JH220
