### ISSUE TITLE
[Feature Request] Restoring messages (/unclear)

### ISSUE THREAD

**Issue by nsde** [JH220/discord-clearchatbot#4]
> Requested by `ØG Kazama#8658` on the support Discord server

# Concept
`/unclear` - A command for recovering deleted messages.

# Implementation
- Whenever `/clear` is being ran, the deleted messages are being **saved** for *x* minutes
- **Webhooks** could be used to send 'fake' the recovered messages that seem similar to actual ones

**Comment by Neko-Life** [comment]
This seems like Discord API abuse

**Comment by nsde** [comment]
> This seems like Discord API abuse

Please share a link or source proving your point.

**Comment by JH220** [comment]
No longer so easily possible due to message intent.
Will therefore be closed for now.

**Comment by nsde** [comment]
@JH220 Please read #2 first !
